language: cpp

sudo: required

cache:
  - directories:
    - ~/deb_pack_cache

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
      - ubuntu-toolchain-r-test
    #packages:
      #- gcc-6
      #- g++-6
      #- libstdc++6
      #- clang-5.0
      #- clang++-5.0
      #- python3.5

# Download the dependencies if it is not cached
# All the "echo" and "ls" in "before_script" can be remove since they are only used for debugging.
before_script:
  - echo "Print content of deb_pack_cache"
  - ls ~/deb_pack_cache
  - echo "Check whether apt-get has no cache"
  - ls /var/cache/apt/archives
  -
  - echo "Start loading cache"
  - |
    exist() {
        [ -e "$1" ]
    }
  - |
    if exist ~/deb_pack_cache/*.deb
    then
        sudo mv ~/deb_pack_cache/*.deb /var/cache/apt/archives/
        ls /var/cache/apt/archives
    fi
  -
  - echo "Start to install software"
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends --no-install-suggests gcc-6 g++-6 libstdc++6 clang-5.0 clang++-5.0 python3.5
  -
  - echo "Start updating the cache"
  - cp /var/cache/apt/archives/*deb ~/deb_pack_cache/

script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - g++ --version
  - ls /usr/lib32/libstdc++.so.*
  - cd src/count_character
  - clang++-5.0 -std=c++14 test.cc
  - ./a.out
